#/*
# * Copyright (c) 2026 Advanced Micro Devices, Inc. All Rights Reserved.
# *
# * Author:
# *       Bruce Ashfield <bruce.ashfield@amd.com>
# *
# * SPDX-License-Identifier: BSD-3-Clause
# */

"""
Assemble a system-top.dts from a compose_devices devices YAML.

Last big architectural piece of the sdt-from-linux pipeline:
turns the openamp,domain-v1,devices inventory compose_devices emits
into a structurally valid System Device Tree the existing Lopper
domain-processing flow can consume.

MVP scope (this iteration): self-contained DTS capturing the SDT
shape — multi-cluster wrappers, memory and reserved-memory regions,
shared bus skeleton, per-device stub nodes with the inventory-derived
properties (reg, status, source tags, pm_node, bootph), aliases
pass-through, and a /domains placeholder. Per-device detail (clocks,
interrupts, vendor properties) that the inventory doesn't carry is
NOT reproduced here — those nodes are stubs. Future iterations can
walk the original Linux/Zephyr source trees during assembly to copy
full node content verbatim; for the MVP this is honest about what
the inventory gives us and matches the existing tooling pattern
(an SDT-shaped intermediate the domain assists slice into per-OS
DTs).

Usage:
    # Two-step (compose_devices then assemble_sdt):
    lopper <linux-flat.dts> - -- compose_devices --board <name> \\
        [--zephyr-dt <zephyr-flat.dts>] -o /tmp/devices.yaml
    lopper - - -- assemble_sdt --devices /tmp/devices.yaml \\
        -o /tmp/system-top.dts

    # The two-step shape keeps assemble_sdt independent of the
    # source trees compose_devices reads — its input is purely the
    # devices YAML, so tests can exercise it in isolation.

Options:
    -v, --verbose          Enable verbose output
    -d, --devices PATH     Input devices YAML (required)
    -o, --output PATH      Output system-top.dts path (required)
"""

import getopt
import logging
import os
import re
import sys

import lopper
import lopper.log

lopper.log._init(__name__)


_AUTOGEN_HEADER = """\
/*
 * AUTO-GENERATED by lopper assemble_sdt from a compose_devices
 * devices YAML. Do NOT edit this file by hand — re-run the pipeline
 * with the appropriate inputs (Linux DT + optional Zephyr DT +
 * per-board augment.yaml) to regenerate.
 *
 * This is a System Device Tree intermediate. Per-device detail
 * (clocks, interrupts, vendor properties) is not reproduced from the
 * source DTs in this MVP — peripheral nodes are stubs carrying just
 * the inventory facts (reg, status, source tag, pm_node, bootph).
 * Downstream tooling (lopper domain assists) consumes this as input
 * to produce per-OS device trees.
 */
"""


def is_compat(node, compat_string_to_test):
    """Assist-framework dispatch for assemble_sdt."""
    if re.search("assemble-sdt,assemble-v1", compat_string_to_test):
        return assemble_sdt
    if re.search("module,assemble_sdt", compat_string_to_test):
        return assemble_sdt
    return ""


def usage():
    print("""
   Usage: assemble_sdt --devices <yaml> -o <output.dts>

      -v, --verbose          Enable verbose output
      -d, --devices PATH     Input devices YAML (from compose_devices)
      -o, --output PATH      Output system-top.dts path

   Turns an openamp,domain-v1,devices YAML into a system-top.dts. The
   intermediate format is the existing compose_devices output, so this
   assist is independent of the source DTs that produced it.

   Example:
      lopper - - -- assemble_sdt --devices devices.yaml -o system-top.dts
    """)


def _normalize_inventory(dom):
    """Coerce the YAML-parsed domain block into list-shaped inventory.

    LopperYAML collapses single-element lists to bare dicts on emit;
    yaml.safe_load brings them back as dicts. Normalise so the
    assembler can iterate uniformly.
    """
    out = {}
    for key in ('cpus', 'memory', 'sram', 'access'):
        val = dom.get(key)
        if val is None:
            out[key] = []
        elif isinstance(val, dict):
            out[key] = [val]
        else:
            out[key] = list(val)
    return out


def _arch_label(compatible):
    """Short label for the cluster-wrapper node name.

    'arm,cortex-a72' → 'a72'; 'arm,cortex-r5f' → 'r5'; 'arm,cortex-m4'
    → 'm4'; 'pmc-microblaze' → 'pmc-microblaze'; fallback: the
    compatible itself with separators sanitised.
    """
    if not compatible:
        return 'unknown'
    m = re.match(r'arm,cortex-([a-z][0-9]+)f?$', compatible)
    if m:
        return m.group(1)
    return re.sub(r'[^A-Za-z0-9]+', '_', compatible.replace('arm,', ''))


def _reg_cells(start, size, addr_cells=2, size_cells=2):
    """Format (start, size) as a `reg = <…>` cell list at the given cell counts."""
    cells = []
    if addr_cells == 2:
        if start is None:
            cells.extend(['0x0', '0x0'])
        else:
            cells.append(f'0x{(int(start) >> 32) & 0xffffffff:x}')
            cells.append(f'0x{int(start) & 0xffffffff:x}')
    else:
        cells.append(f'0x{int(start or 0):x}')
    if size_cells == 2:
        if size is None:
            cells.extend(['0x0', '0x0'])
        else:
            cells.append(f'0x{(int(size) >> 32) & 0xffffffff:x}')
            cells.append(f'0x{int(size) & 0xffffffff:x}')
    else:
        cells.append(f'0x{int(size or 0):x}')
    return ' '.join(cells)


def _emit_clusters(cpu_entries):
    """Each cpus entry → a /cpus_<label>: cpus-<label>@<idx> { compatible = "cpus,cluster"; … }.

    SDT structural convention: every CPU cluster (one per architecture
    family on the SoC) sits at the root with cpus,cluster compatible.
    The Linux DT's bare /cpus block gets renamed to cpus-<arch>@0 here.
    Zephyr-sourced clusters are appended as additional siblings.
    """
    lines = []
    for idx, cpu_entry in enumerate(cpu_entries):
        compatible = cpu_entry.get('compatible') or ''
        label = _arch_label(compatible)
        node_label = f'cpus_{label}'
        cluster_name = f'cpus-{label}@{idx}'
        cpumask = int(cpu_entry.get('cpumask', 0))
        source = cpu_entry.get('source')

        lines.append(f'    {node_label}: {cluster_name} {{')
        lines.append('        #address-cells = <1>;')
        lines.append('        #size-cells = <0>;')
        lines.append('        compatible = "cpus,cluster";')
        if source:
            lines.append(f'        lopper-source = "{source}";')

        # Decode the cpumask bitmap into per-core sub-nodes.
        # Bit N set → core@N exists with reg = <N>.
        any_cpu = False
        for cpu_idx in range(64):
            if not (cpumask & (1 << cpu_idx)):
                continue
            any_cpu = True
            lines.append('')
            lines.append(f'        cpu@{cpu_idx} {{')
            lines.append('            device_type = "cpu";')
            if compatible:
                lines.append(f'            compatible = "{compatible}";')
            lines.append(f'            reg = <0x{cpu_idx:x}>;')
            lines.append('        };')

        if not any_cpu:
            lines.append(f'        /* cpumask=0x{cpumask:x} — no cores decoded */')

        lines.append('    };')
        lines.append('')
    return lines


def _emit_memory(memory_entries):
    """memory: list → /memory@<addr> nodes at the root."""
    lines = []
    for mem in memory_entries:
        dev = mem.get('dev', 'memory@0')
        # Use a sanitised version of dev as the node name; the @addr
        # portion is what dtc/dts requires for memory nodes.
        node_name = dev
        if '@' not in node_name:
            # synthesise an @addr if absent
            start = mem.get('start') or 0
            node_name = f'memory@{int(start):x}'
        lines.append(f'    {node_name} {{')
        lines.append('        device_type = "memory";')
        start = mem.get('start')
        size = mem.get('size')
        lines.append(f'        reg = <{_reg_cells(start, size)}>;')
        if mem.get('source'):
            lines.append(f'        lopper-source = "{mem["source"]}";')
        lines.append('    };')
        lines.append('')
    return lines


def _emit_reserved_memory(sram_entries, memory_entries):
    """sram/memory with no-map=true (typically augment carve-outs) → /reserved-memory/<...>."""
    lines = []
    candidates = []
    for entry in sram_entries + memory_entries:
        if entry.get('no-map') or entry.get('reusable'):
            candidates.append(entry)
    if not candidates:
        return lines
    lines.append('    reserved-memory {')
    lines.append('        #address-cells = <2>;')
    lines.append('        #size-cells = <2>;')
    lines.append('        ranges;')
    for entry in candidates:
        dev = entry.get('dev', 'reserved')
        # Preserve the inventory-supplied name; append the @addr that
        # dtc requires for nodes with a reg property.
        if '@' in dev:
            node_name = dev
        else:
            start = entry.get('start') or 0
            node_name = f'{dev}@{int(start):x}'
        lines.append('')
        lines.append(f'        {node_name} {{')
        start = entry.get('start')
        size = entry.get('size')
        lines.append(f'            reg = <{_reg_cells(start, size)}>;')
        if entry.get('no-map'):
            lines.append('            no-map;')
        if entry.get('reusable'):
            lines.append('            reusable;')
        if entry.get('source'):
            lines.append(f'            lopper-source = "{entry["source"]}";')
        lines.append('        };')
    lines.append('    };')
    lines.append('')
    return lines


def _emit_access_stub(entry, indent='        '):
    """Emit a per-device stub node body for one access entry.

    Shared by _emit_axi_bus (addressable peripherals) and the
    toplevel-emitter (addressless entries like dcc, versal_firmware).
    """
    lines = []
    dev = entry.get('dev', '')
    lines.append(f'{indent}{dev} {{')
    m = re.search(r'@([0-9a-fA-F]+)$', dev)
    if m:
        addr = int(m.group(1), 16)
        # 1 KiB placeholder size — inventory doesn't carry the real reg
        # extent. M11+ can pull the actual size from the source tree.
        lines.append(f'{indent}    reg = <{_reg_cells(addr, 0x1000)}>;')
    status = entry.get('status')
    if status:
        lines.append(f'{indent}    status = "{status}";')
    if entry.get('label'):
        lines.append(f'{indent}    /* label = {entry["label"]} */')
    if entry.get('pm_node'):
        lines.append(f'{indent}    lopper-pm-node = "{entry["pm_node"]}";')
    if entry.get('bootph'):
        bp = entry['bootph']
        if isinstance(bp, list):
            bp = ','.join(bp)
        lines.append(f'{indent}    lopper-bootph = "{bp}";')
    if entry.get('source'):
        lines.append(f'{indent}    lopper-source = "{entry["source"]}";')
    lines.append(f'{indent}}};')
    return lines


def _emit_axi_bus(access_entries):
    """Addressable access entries → per-device stub nodes under a shared simple-bus.

    Stubs that share the same name (linux+zephyr views of the same
    peripheral after the merge) are emitted once.
    """
    lines = []
    lines.append('    amba: axi {')
    lines.append('        compatible = "simple-bus";')
    lines.append('        #address-cells = <2>;')
    lines.append('        #size-cells = <2>;')
    lines.append('        ranges;')

    seen = {}
    for entry in access_entries:
        dev = entry.get('dev', '')
        if not dev:
            continue
        # Only addressable entries belong on the axi bus.
        if not re.search(r'@([0-9a-fA-F]+)$', dev):
            continue
        if dev in seen:
            continue
        seen[dev] = True

        lines.append('')
        lines.extend(_emit_access_stub(entry, indent='        '))

    lines.append('    };')
    lines.append('')
    return lines


def _emit_toplevel_access(access_entries):
    """Addressless access entries (dcc, versal_firmware, pmu, fpga-region…)
    live at the root, not under axi — matches how Linux DTSes structure them.

    Emitted AFTER the axi bus so the document reads top-down: clusters,
    memory, axi peripherals, addressless devices, aliases, chosen, domains.
    """
    lines = []
    seen = {}
    for entry in access_entries:
        dev = entry.get('dev', '')
        if not dev:
            continue
        # Skip addressable entries — those went under axi.
        if re.search(r'@([0-9a-fA-F]+)$', dev):
            continue
        if dev in seen:
            continue
        seen[dev] = True

        lines.extend(_emit_access_stub(entry, indent='    '))
        lines.append('')
    return lines


def _emit_aliases(aliases):
    """aliases dict → /aliases { foo = "path"; … }."""
    if not aliases:
        return []
    lines = ['    aliases {']
    for name, target in sorted(aliases.items()):
        lines.append(f'        {name} = "{target}";')
    lines.append('    };')
    lines.append('')
    return lines


def _emit_domains_placeholder(soc_family, board):
    """Minimal /domains block — partition intent expansion is M11+."""
    lines = ['    domains {']
    lines.append('        #address-cells = <2>;')
    lines.append('        #size-cells = <2>;')
    lines.append('        /* Partition intent goes here. Populate via openamp,domain-v1')
    lines.append('         * YAML overlays processed by Lopper\'s existing domain assists. */')
    lines.append('    };')
    lines.append('')
    return lines


def emit_sdt(devices_yaml_text):
    """Build the full system-top.dts text from a parsed devices YAML.

    No input-path is recorded in the header so the output is
    reproducible across different invocations of the same inputs
    (tests can byte-diff against committed goldens).
    """
    import yaml as _y
    parsed = _y.safe_load(devices_yaml_text) or {}
    domains = parsed.get('domains') or {}
    if not domains:
        raise RuntimeError("devices YAML has no /domains block; cannot assemble")

    # The compose_devices output has exactly one domain block under
    # `domains:`. Grab whichever it is.
    dom_name, dom = next(iter(domains.items()))
    inventory = _normalize_inventory(dom)

    soc_family = dom.get('soc_family', '')
    board = dom.get('board', '')
    model = dom.get('model', '')

    # Root compatible: prefer the board-specific compatible first
    # (matches how Linux DTSes are conventionally ordered:
    # most-specific → most-generic).
    compats = []
    if board:
        compats.append(board)
    if soc_family and soc_family not in compats:
        compats.append(soc_family)

    lines = []
    lines.append('/dts-v1/;')
    lines.append('')
    lines.append(_AUTOGEN_HEADER)
    lines.append('/ {')
    lines.append('    #address-cells = <2>;')
    lines.append('    #size-cells = <2>;')
    if compats:
        compat_str = ', '.join(f'"{c}"' for c in compats)
        lines.append(f'    compatible = {compat_str};')
    if model:
        lines.append(f'    model = "{model}";')
    if soc_family:
        lines.append(f'    lopper-soc-family = "{soc_family}";')
    if board:
        lines.append(f'    lopper-board = "{board}";')
    lines.append('')

    lines.extend(_emit_clusters(inventory['cpus']))
    lines.extend(_emit_memory(inventory['memory']))
    lines.extend(_emit_reserved_memory(inventory['sram'], inventory['memory']))
    lines.extend(_emit_axi_bus(inventory['access']))
    lines.extend(_emit_toplevel_access(inventory['access']))
    lines.extend(_emit_aliases(dom.get('aliases') or {}))
    lines.extend(_emit_domains_placeholder(soc_family, board))

    lines.append('};')
    return '\n'.join(lines) + '\n'


def assemble_sdt(tgt_node, sdt, options):
    """Assist entry point. Ignores the main sdt input — assemble_sdt's
    real input is the --devices YAML, supplied via the CLI args.
    """
    try:
        verbose = options['verbose']
    except KeyError:
        verbose = 0
    try:
        args = options['args']
    except KeyError:
        args = []

    try:
        opts, _ = getopt.getopt(args, "hvd:o:",
                                ["help", "verbose", "devices=", "output="])
    except getopt.GetoptError as e:
        lopper.log._error(f"assemble_sdt: invalid option: {e}")
        usage()
        return False

    devices_path = None
    output_path = None
    for o, a in opts:
        if o in ('-h', '--help'):
            usage()
            return True
        elif o in ('-v', '--verbose'):
            verbose += 1
        elif o in ('-d', '--devices'):
            devices_path = a
        elif o in ('-o', '--output'):
            output_path = a

    if verbose > 1:
        lopper.log._level(logging.DEBUG, __name__)
    elif verbose > 0:
        lopper.log._level(logging.INFO, __name__)

    if not devices_path:
        lopper.log._error("assemble_sdt: --devices is required")
        usage()
        return False
    if not output_path:
        lopper.log._error("assemble_sdt: --output is required")
        usage()
        return False
    if not os.path.isfile(devices_path):
        lopper.log._error(f"assemble_sdt: devices YAML not found: {devices_path}")
        return False

    lopper.log._info(f"assemble_sdt: input devices YAML: {devices_path}")
    lopper.log._info(f"assemble_sdt: output system-top.dts: {output_path}")

    try:
        with open(devices_path) as fh:
            text = fh.read()
        dts_text = emit_sdt(text)
    except Exception as e:
        lopper.log._error(f"assemble_sdt: failed: {e}")
        return False

    out_dir = os.path.dirname(output_path)
    if out_dir and not os.path.exists(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    with open(output_path, 'w') as fh:
        fh.write(dts_text)
    lopper.log._info(f"assemble_sdt: success — {len(dts_text)} bytes written")
    return True
